Repository e0404/matRad, pull requests merged in 2023-11, with the labels that each got.

#640 Implementation of the analytical dose engine
  doseCalc/+DoseEngines/@matRad_DoseEngineBase/getAvailableEngines.m
  doseCalc/+DoseEngines/matRad_ParticleAnalyticalBortfeldEngine.m
  gui/widgets/matRad_WorkflowWidget.m
  thirdParty/license.txt
  thirdParty/pu.m
Labels: enhancement, refactor

#600 Incorperate multiple weighted lateral Gaussian Profiles
  doseCalc/+DoseEngines/matRad_ParticleAnalyticalBortfeldEngine.m
  doseCalc/+DoseEngines/matRad_ParticleHongPencilBeamEngine.m
  doseCalc/+DoseEngines/matRad_ParticlePencilBeamEngineAbstract.m
Labels: enhancement

#674 Import dicom with HFP and FFP orientations
  dicom/matRad_convRtssContours2Indices.m
  dicom/matRad_importDicom.m
  dicom/matRad_importDicomCt.m
Labels: bug, enhancement
