Repository e0404/matRad, pull requests merged in 2024-07, with the labels that each got.

#739 Update to overriding of Default values in the dose engines
  matRad/MatRad_Config.m
  matRad/doseCalc/+DoseEngines/@matRad_DoseEngineBase/matRad_DoseEngineBase.m
  matRad/doseCalc/+DoseEngines/matRad_ParticleMCsquareEngine.m
  matRad/tools/matRad_recursiveFieldAssignment.m
  test/autoExampleTest/test_examples.m
  test/tools/test_recursiveFieldAssignment.m
Labels: bug

#743 New Workflow for managing stale issues and PRs
  .github/stale.yml
  .github/workflows/stale.yml
Labels: devops

#718 Brachytherapy Integration (Update)
  AUTHORS.txt
  examples/matRad_example15_brachy.m
  examples/matRad_example16_photonMC_MLC.m
  matRad.m
  matRad/basedata/brachy_HDR.mat
  matRad/basedata/brachy_LDR.mat
  matRad/bioModels/matRad_BiologicalModel.m
  matRad/bioModels/matRad_bioModel.m
  matRad/brachytherapy/additionalScripts/matRad_plot2DFunc.m
  matRad/brachytherapy/matRad_getDistanceMatrix.m
  matRad/brachytherapy/matRad_getTemplateRoot.m
  matRad/doseCalc/+DoseEngines/@matRad_DoseEngineBase/initDoseCalc.m
  matRad/doseCalc/+DoseEngines/@matRad_DoseEngineBase/matRad_DoseEngineBase.m
  matRad/doseCalc/+DoseEngines/matRad_TG43BrachyEngine.m
  matRad/gui/widgets/matRad_PlanWidget.m
  matRad/matRad_fluenceOptimization.m
  matRad/matRad_generateStf.m
  matRad/optimization/optimizer/matRad_OptimizerSimulannealbnd.m
  matRad_runTests.m
  test/autoExampleTest/test_examples.m
  test/brachy/data/calcDoseSimpleTestStruct.mat
  test/brachy/data/examplePlnAndStf.mat
  test/brachy/data/referenceDoseCalculation.mat
  test/brachy/matRad_gammaPassRate2D.m
  test/brachy/test_calcBrachyDose.m
  test/brachy/test_generateBrachyStf.m
  test/doseCalc/test_baseEngine.m
  test/matRad_unitTestTextManipulation.m
  test/optimizers/test_optimizerIPOPT.m
Labels: enhancement
