Repository e0404/matRad, pull requests merged in 2024-09, with the labels that each got.

#764 Added warning: range scnearios are not implemented in MC simulations
  matRad/doseCalc/+DoseEngines/matRad_ParticleMCsquareEngine.m
  matRad/doseCalc/+DoseEngines/matRad_TopasMCEngine.m
Labels: bug

#766 structure visibility change resets viewing widget to isocenter
  matRad/gui/widgets/matRad_DVHStatsWidget.m
  matRad/gui/widgets/matRad_DVHWidget.m
  matRad/gui/widgets/matRad_StructureVisibilityWidget.m
Labels: bug

#763 Stf Generators Refactor
  examples/matRad_example12_simpleParticleMonteCarlo.m
  examples/matRad_example15_brachy.m
  examples/matRad_example2_photons.m
  matRad/MatRad_Config.m
  matRad/basedata/helium_Generic.mat
  matRad/matRad_generateStf.m
  matRad/optimization/optimizer/matRad_OptimizerFmincon.m
  matRad/steering/matRad_StfGeneratorBase.m
  matRad/steering/matRad_StfGeneratorBrachy.m
  matRad/steering/matRad_StfGeneratorExternalRayBixelAbstract.m
  matRad/steering/matRad_StfGeneratorParticleIMPT.m
  matRad/steering/matRad_StfGeneratorParticleRayBixelAbstract.m
  matRad/steering/matRad_StfGeneratorParticleSingleBeamlet.m
  matRad/steering/matRad_StfGeneratorPhotonIMRT.m
  matRad/steering/matRad_StfGeneratorPhotonRayBixelAbstract.m
  matRad/steering/matRad_StfGeneratorPhotonSingleBeamlet.m
  matRad/util/matRad_generateSingleBixelStf.m
  test/core/test_generateStf.m
  test/steering/test_generateBrachyStf.m
  test/steering/test_stfGEneratorParticleIMPT.m
  test/steering/test_stfGeneratorParticleBeamlet.m
  test/steering/test_stfGeneratorPhotonBixel.m
  test/steering/test_stfGeneratorPhotonIMRT.m
  test/steering/test_stfGeneratorsBase.m
Labels: refactor

#768 generate body contour
  matRad/util/matRad_generateBodyContour.m
  test/util/test_generateBodyContour.m
Labels: enhancement
